### ISSUE TITLE
please fix Gauss not visible after installing this mod

### ISSUE THREAD

**Issue by RebalClause** [andtheherois/3DSS-for-Gunslinger-AA12-AK101-AK103-BP-Gauss-Rifle#1]

**Comment by andtheherois** [comment]
> _No description provided._

Do you have the base mod installed?

**Comment by RebalClause** [comment]
Yeah install both 3Dss.gs and Ori Weapon  from Google drive

**Comment by andtheherois** [comment]
Can you post a picture of what you see?

**Comment by RebalClause** [comment]
![Uploading Screenshot (33).png…]()

**Comment by andtheherois** [comment]
you most likely have something overriding the position or do not have the base mod. ;
